/* This Proc Format program was automatically generated by Stat/Transfer ver.12.1.334.0516 */

/* ENCODING CP1252 */



libname library 'C:/Users/Rosie/Documents/new projects/Knowledge networks where couples meet/web site documentation prep wave 5/sas version/' ;

proc format library = library ;
   value W5_SOURCE
      1 = 'online'  
      2 = 'phone' ;
   value W5_COMPLETE
      0 = 'eligible but not completed'  
      1 = 'wave 5 completed' ;
   value W5_STATUS
      1 = 'Active'  
      2 = 'Withdrawn'  
      3 = 'Retired'  
      4 = 'Do not call' ;
   value W5_XQUAL
      0 = 'not qualified for wave 5'  
      1 = 'qualified for wave 5' ;
   value W5_XMARR
      1 = 'married'  
      2 = 'unmarried partners' ;
   value W5_XCIVI
      0 = 'no civil union or DP prior to wave 5'  
      1 = 'yes civil union or DP prior to wave 5' ;
   value W5_XMONT
      1 = 'January'  
      2 = 'February'  
      3 = 'March'  
      4 = 'April'  
      5 = 'May'  
      6 = 'June'  
      7 = 'July'  
      8 = 'August'  
      9 = 'September'  
      10 = 'October'  
      11 = 'November'  
      12 = 'December' ;
   value W5_XCIVM
      1 = 'January'  
      2 = 'February'  
      3 = 'March'  
      4 = 'April'  
      5 = 'May'  
      6 = 'June'  
      7 = 'July'  
      8 = 'August'  
      9 = 'September'  
      10 = 'October'  
      11 = 'November'  
      12 = 'December' ;
   value W5_Q1F
      -1 = 'Refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W5_Q2F
      -1 = 'Refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W5_SEX_F
      -1 = 'Refused'  
      1 = 'Once a day or more'  
      2 = '3 to 6 times a week'  
      3 = 'Once or twice a week'  
      4 = '2 to 3 times a month'  
      5 = 'Once a month or less' ;
   value W5_P_MON
      -1 = 'Refused'  
      1 = 'Yes, I expect [name] will only have sex with me'  
      2 = 'No, I expect [name] to have sex with other people besides me' ;
   value W5_IDENT
      -1 = 'Refused'  
      1 = 'heterosexual or straight'  
      2 = 'gay'  
      3 = 'lesbian'  
      4 = 'bisexual'  
      5 = 'Something else' ;
   value W5_OUTNE
      -1 = 'Refused'  
      1 = 'All or most of them'  
      2 = 'Some of them'  
      3 = 'Only a few of them'  
      4 = 'None of them' ;
   value W5_Q3F
      -1 = 'Refused'  
      1 = 'divorce'  
      2 = 'separation with no divorce'  
      3 = '[name] passed away, is deceased' ;
   value W5_Q4F
      -1 = 'Refused'  
      1 = 'I wanted the [divorce/separation] more.'  
      2 = '[name] wanted the [divorce/separation] more.'  
      3 = 'We both equally wanted the [divorce/separation].' ;
   value W5_MBTIM
      -1 = 'Refused'  
      1 = 'January'  
      2 = 'February'  
      3 = 'March'  
      4 = 'April'  
      5 = 'May'  
      6 = 'June'  
      7 = 'July'  
      8 = 'August'  
      9 = 'September'  
      10 = 'October'  
      11 = 'November'  
      12 = 'December' ;
   value W5_Q5F
      -1 = 'Refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W5_Q6F
      -1 = 'Refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W5_Q7F
      -1 = 'Refused'  
      1 = 'yes, married [name]'  
      2 = 'no, did not marry [name]' ;
   value W5_MAR_M
      -1 = 'Refused'  
      1 = 'January'  
      2 = 'February'  
      3 = 'March'  
      4 = 'April'  
      5 = 'May'  
      6 = 'June'  
      7 = 'July'  
      8 = 'August'  
      9 = 'September'  
      10 = 'October'  
      11 = 'November'  
      12 = 'December' ;
   value W5_Q8F
      -1 = 'Refused'  
      1 = 'No, we have not gotten a domestic partnership or civil union agreement'  
      2 = 'Yes, we have gotten a domestic partnership or civil union agreement' ;
   value W5_CIV_Y
      -1 = 'Refused' ;
   value W5_CIV_M
      -1 = 'Refused'  
      1 = 'January'  
      2 = 'February'  
      3 = 'March'  
      4 = 'April'  
      5 = 'May'  
      6 = 'June'  
      7 = 'July'  
      8 = 'August'  
      9 = 'September'  
      10 = 'October'  
      11 = 'November'  
      12 = 'December' ;
   value W5_Q9F
      -1 = 'Refused'  
      1 = 'We broke up'  
      2 = '[name] passed away, is deceased' ;
   value W5_Q10F
      -1 = 'Refused'  
      1 = 'I wanted to break up more'  
      2 = '[name] wanted to break up more'  
      3 = 'We both equally wanted to break up' ;
   value W5_NONMB_MONTH
      -1 = 'Refused'  
      1 = 'January'  
      2 = 'February'  
      3 = 'March'  
      4 = 'April'  
      5 = 'May'  
      6 = 'June'  
      7 = 'July'  
      8 = 'August'  
      9 = 'September'  
      10 = 'October'  
      11 = 'November'  
      12 = 'December' ;
   value W5_BROKE_UP
      0 = 'still together'  
      1 = 'broke up'  
      2 = 'partner deceased' ;
   value W2345_COMBO_BREAKUP
      0 = 'still together at w5 or some follow-up w/o breakup'  
      1 = 'broke up at wave 2,3,4, or 5' ;
   value YES_NO
      0 = 'No'  
      1 = 'Yes' ;
   value PP5_PPAGE
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value PP5_PPAGECAT
      1 = '18-24'  
      2 = '25-34'  
      3 = '35-44'  
      4 = '45-54'  
      5 = '55-64'  
      6 = '65-74'  
      7 = '75+'  
      99 = 'Under 18' ;
   value PP5_PPAGECT4F
      1 = '18-29'  
      2 = '30-44'  
      3 = '45-59'  
      4 = '60+'  
      99 = 'Under 18' ;
   value PP5_PPEDUC
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'No formal education'  
      2 = '1st, 2nd, 3rd, or 4th grade'  
      3 = '5th or 6th grade'  
      4 = '7th or 8th grade'  
      5 = '9th grade'  
      6 = '10th grade'  
      7 = '11th grade'  
      8 = '12th grade NO DIPLOMA'  
      9 = 'HIGH SCHOOL GRADUATE - high school DIPLOMA or the equivalent (GED)'  
      10 = 'Some college, no degree'  
      11 = 'Associate degree'  
      12 = 'Bachelors degree'  
      13 = 'Masters degree'  
      14 = 'Professional or Doctorate degree' ;
   value PP5_PPEDUCAT
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Less than high school'  
      2 = 'High school'  
      3 = 'Some college'  
      4 = 'Bachelor''s degree or higher' ;
   value PP5_PPETHM
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'White, Non-Hispanic'  
      2 = 'Black, Non-Hispanic'  
      3 = 'Other, Non-Hispanic'  
      4 = 'Hispanic'  
      5 = '2+ Races, Non-Hispanic' ;
   value PP5_PPGENDER
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Male'  
      2 = 'Female' ;
   value PP5_PPHHSIZE
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value PP5_PPHOUSE
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'A one-family house detached from any other house'  
      2 = 'A one-family house attached to one or more houses'  
      3 = 'A building with 2 or more apartments'  
      4 = 'A mobile home'  
      5 = 'Boat, RV, van, etc.' ;
   value PP5_PPINCIMP
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Less than $5,000'  
      2 = '$5,000 to $7,499'  
      3 = '$7,500 to $9,999'  
      4 = '$10,000 to $12,499'  
      5 = '$12,500 to $14,999'  
      6 = '$15,000 to $19,999'  
      7 = '$20,000 to $24,999'  
      8 = '$25,000 to $29,999'  
      9 = '$30,000 to $34,999'  
      10 = '$35,000 to $39,999'  
      11 = '$40,000 to $49,999'  
      12 = '$50,000 to $59,999'  
      13 = '$60,000 to $74,999'  
      14 = '$75,000 to $84,999'  
      15 = '$85,000 to $99,999'  
      16 = '$100,000 to $124,999'  
      17 = '$125,000 to $149,999'  
      18 = '$150,000 to $174,999'  
      19 = '$175,000 or more' ;
   value PP5_PPMARIT
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Married'  
      2 = 'Widowed'  
      3 = 'Divorced'  
      4 = 'Separated'  
      5 = 'Never married'  
      6 = 'Living with partner' ;
   value PP5_PPMSACAT
      0 = 'non-Metro'  
      1 = 'Metro' ;
   value PP5_PPREG4F
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Northeast'  
      2 = 'Midwest'  
      3 = 'South'  
      4 = 'West' ;
   value PP5_PPREG9F
      1 = 'New England'  
      2 = 'Mid-Atlantic'  
      3 = 'East-North Central'  
      4 = 'West-North Central'  
      5 = 'South Atlantic'  
      6 = 'East-South Central'  
      7 = 'West-South Central'  
      8 = 'Mountain'  
      9 = 'Pacific' ;
   value PP5_PPRENT
      1 = 'Owned or being bought by you or someone in household'  
      2 = 'rented for cash'  
      3 = 'Occupied without payment' ;
   value PP5_PPT01F
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value PP5_PPT612F
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value PP5_PPT1317F
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value PP5_PPT18OV
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value PP5_PPWORK
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Working - as a paid employee'  
      2 = 'Working - self-employed'  
      3 = 'Not working - on temporary layoff from a job'  
      4 = 'Not working - looking for work'  
      5 = 'Not working - retired'  
      6 = 'Not working - disabled'  
      7 = 'Not working - other' ;
   value PP5_PPNET
      0 = 'No'  
      1 = 'Yes' ;
   value PPMARIT_2014F
      -2 = 'Not asked'  
      -1 = 'Refused'  
      1 = 'Married'  
      2 = 'Widowed'  
      3 = 'Divorced'  
      4 = 'Separated'  
      5 = 'Never married'  
      6 = 'Living with partner' ;
   value PPMARIT_2013F
      -2 = 'Not asked'  
      -1 = 'Refused'  
      1 = 'Married'  
      2 = 'Widowed'  
      3 = 'Divorced'  
      4 = 'Separated'  
      5 = 'Never married'  
      6 = 'Living with partner' ;
   value PPMARIT_2012F
      -2 = 'Not asked'  
      -1 = 'Refused'  
      1 = 'Married'  
      2 = 'Widowed'  
      3 = 'Divorced'  
      4 = 'Separated'  
      5 = 'Never married'  
      6 = 'Living with partner' ;
   value PPMARIT_2011F
      -2 = 'Not asked'  
      -1 = 'Refused'  
      1 = 'Married'  
      2 = 'Widowed'  
      3 = 'Divorced'  
      4 = 'Separated'  
      5 = 'Never married'  
      6 = 'Living with partner' ;
   value PPMARIT_2010F
      -2 = 'Not asked'  
      -1 = 'Refused'  
      1 = 'Married'  
      2 = 'Widowed'  
      3 = 'Divorced'  
      4 = 'Separated'  
      5 = 'Never married'  
      6 = 'Living with partner' ;
   value PPMARIT_2009F
      -2 = 'Not asked'  
      -1 = 'Refused'  
      1 = 'Married'  
      2 = 'Widowed'  
      3 = 'Divorced'  
      4 = 'Separated'  
      5 = 'Never married'  
      6 = 'Living with partner' ;
   value PPMARIT_2007F
      -2 = 'Not asked'  
      -1 = 'Refused'  
      1 = 'Married'  
      2 = 'Widowed'  
      3 = 'Divorced'  
      4 = 'Separated'  
      5 = 'Never married'  
      6 = 'Living with partner' ;

proc datasets library = library ;
modify wave5_supplement_v1_sas;
   format w5_source W5_SOURCE.;
   format w5_complete W5_COMPLETE.;
   format w5_status W5_STATUS.;
   format w5x_qualified W5_XQUAL.;
   format w5x_marry W5_XMARR.;
   format w5x_civil W5_XCIVI.;
   format w5x_month W5_XMONT.;
   format w5x_civmonth W5_XCIVM.;
   format     w5_q1 W5_Q1F.;
   format     w5_q2 W5_Q2F.;
   format w5_sex_frequency W5_SEX_F.;
   format w5_p_monogamy W5_P_MON.;
   format w5_identity W5_IDENT.;
   format w5_outness W5_OUTNE.;
   format     w5_q3 W5_Q3F.;
   format     w5_q4 W5_Q4F.;
   format w5_mbtiming_month W5_MBTIM.;
   format     w5_q5 W5_Q5F.;
   format     w5_q6 W5_Q6F.;
   format     w5_q7 W5_Q7F.;
   format w5_mar_month W5_MAR_M.;
   format     w5_q8 W5_Q8F.;
   format w5_civ_year W5_CIV_Y.;
   format w5_civ_month W5_CIV_M.;
   format     w5_q9 W5_Q9F.;
   format    w5_q10 W5_Q10F.;
   format w5_nonmbtiming_month W5_NONMB_MONTH.;
   format w5_broke_up W5_BROKE_UP.;
   format w2345_combo_breakup W2345_COMBO_BREAKUP.;
   format responded_to_w234or5 YES_NO.;
   format pp5_ppage PP5_PPAGE.;
   format pp5_ppagecat PP5_PPAGECAT.;
   format pp5_ppagect4 PP5_PPAGECT4F.;
   format pp5_ppeduc PP5_PPEDUC.;
   format pp5_ppeducat PP5_PPEDUCAT.;
   format pp5_ppethm PP5_PPETHM.;
   format pp5_ppgender PP5_PPGENDER.;
   format pp5_pphhsize PP5_PPHHSIZE.;
   format pp5_pphouse PP5_PPHOUSE.;
   format pp5_ppincimp PP5_PPINCIMP.;
   format pp5_ppmarit PP5_PPMARIT.;
   format pp5_newer YES_NO.;
   format pp5_ppmsacat PP5_PPMSACAT.;
   format pp5_ppreg4 PP5_PPREG4F.;
   format pp5_ppreg9 PP5_PPREG9F.;
   format pp5_pprent PP5_PPRENT.;
   format pp5_ppt01 PP5_PPT01F.;
   format pp5_ppt612 PP5_PPT612F.;
   format pp5_ppt1317 PP5_PPT1317F.;
   format pp5_ppt18ov PP5_PPT18OV.;
   format pp5_ppwork PP5_PPWORK.;
   format pp5_ppnet PP5_PPNET.;
   format ppmarit_2014 PPMARIT_2014F.;
   format ppmarit_2013 PPMARIT_2013F.;
   format ppmarit_2012 PPMARIT_2012F.;
   format ppmarit_2011 PPMARIT_2011F.;
   format ppmarit_2010 PPMARIT_2010F.;
   format ppmarit_2009 PPMARIT_2009F.;
   format ppmarit_2007 PPMARIT_2007F.;
quit;
