/* This Proc Format program was automatically generated by Stat/Transfer ver.12.0.129.0309 */

/* ENCODING CP1252 */



libname library 'C:/Users/Rosie/Documents/new projects/Knowledge networks where couples meet/web site documentation prep wave 4/Sas data for wave 4 supplement/' ;

proc format library = library ;
   value W4_XQUAL
      0 = 'unqualified for wave 4'  
      1 = 'qualified for wave 4' ;
   value W4_STATUS
      1 = 'Active'  
      2 = 'Withdrawn'  
      3 = 'Retired'  
      4 = 'Do not call' ;
   value YES_NO
      0 = 'No'  
      1 = 'Yes' ;
   value W4_SOURCE
      1 = 'On-line'  
      2 = 'Telephone' ;
   value W4_XTYPE
      1 = 'same-sex couple'  
      2 = 'different sex couple' ;
   value W4_XMONT
      1 = 'January'  
      2 = 'February'  
      3 = 'March'  
      4 = 'April'  
      5 = 'May'  
      6 = 'June'  
      7 = 'July'  
      8 = 'August'  
      9 = 'September'  
      10 = 'October'  
      11 = 'November'  
      12 = 'December' ;
   value W4_XMARR
      1 = 'Married'  
      2 = 'Unmarried partners' ;
   value W4_XCIVI
      0 = 'No'  
      1 = 'Yes' ;
   value XSS
      1 = 'Yes'  
      2 = 'No' ;
   value W4_Q1F
      -1 = 'Refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W4_Q2F
      -1 = 'Refused'  
      1 = 'yes'  
      2 = 'no' ;
   value W4_QUALI
      -1 = 'Refused'  
      1 = 'Excellent'  
      2 = 'Good'  
      3 = 'Fair'  
      4 = 'Poor'  
      5 = 'Very Poor' ;
   value W4_ATTRA
      -1 = 'Refused'  
      1 = 'very attractive'  
      2 = 'moderately attractive'  
      3 = 'slightly attractive'  
      4 = 'not at all attractive' ;
   value W4_ATTRACTIVE_PARTNER
      -1 = 'Refused'  
      1 = 'very attractive'  
      2 = 'moderately attractive'  
      3 = 'slightly attractive'  
      4 = 'not at all attractive' ;
   value W4_Q3F
      -1 = 'Refused'  
      1 = 'divorce'  
      2 = 'separation with no divorce'  
      3 = '[xnamep] passed away, is deceased' ;
   value W4_Q4F
      -1 = 'Refused'  
      1 = 'I wanted the [divorce/separation] more'  
      2 = '[xname] wanted the [divorce/separation] more'  
      3 = 'We both equally wanted the [divorce/separation]' ;
   value W4_MBTIM
      1 = '2010'  
      2 = '2011'  
      3 = '2012'  
      4 = '2013' ;
   value W4_MBTIMING_MONTH
      1 = 'January'  
      2 = 'February'  
      3 = 'March'  
      4 = 'April'  
      5 = 'May'  
      6 = 'June'  
      7 = 'July'  
      8 = 'August'  
      9 = 'September'  
      10 = 'October'  
      11 = 'November'  
      12 = 'December' ;
   value W4_Q7F
      -1 = 'Refused'  
      1 = 'Yes, married [xnamep]'  
      2 = 'No, did not marry [xnamep]' ;
   value W4_MAR_M
      1 = 'January'  
      2 = 'February'  
      3 = 'March'  
      4 = 'April'  
      5 = 'May'  
      6 = 'June'  
      7 = 'July'  
      8 = 'August'  
      9 = 'September'  
      10 = 'October'  
      11 = 'November'  
      12 = 'December' ;
   value W4_Q8_A
      -1 = 'Refused'  
      1 = 'No, we have not gotten a domestic partnership or civil union agreement'  
      2 = 'Yes, we have gotten a domestic partnership or civil union agreement' ;
   value W4_Q8_B
      -1 = 'Refused'  
      1 = 'No, we have not gotten a domestic partnership or civil union agreement'  
      2 = 'Yes, we have gotten a domestic partnership or civil union agreement' ;
   value W4_Q9F
      -1 = 'Refused'  
      1 = 'We broke up'  
      2 = '[xnamep] passed away, is deceased'  
      3 = '[xnamep] passed away, is deceased' ;
   value W4_Q10F
      -1 = 'Refused'  
      1 = 'I wanted to break up more'  
      2 = '[xnamep] , wanted the break up more'  
      3 = 'We both equally wanted to break up' ;
   value W4_NMBTIME_MONTH
      1 = 'January'  
      2 = 'February'  
      3 = 'March'  
      4 = 'April'  
      5 = 'May'  
      6 = 'June'  
      7 = 'July'  
      8 = 'August'  
      9 = 'September'  
      10 = 'October'  
      11 = 'November'  
      12 = 'December' ;
   value BROKE_UP
      0 = 'still together'  
      1 = 'broke up'  
      2 = 'partner passed away' ;
   value W234_COMBO_BREAKUP
      0 = 'still together at w4, or some follow-up w/o break-up'  
      1 = 'broke up at wave 2, 3, or 4' ;
   value P4_PPEDUC
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'No formal education'  
      2 = '1st, 2nd, 3rd, or 4th grade'  
      3 = '5th or 6th grade'  
      4 = '7th or 8th grade'  
      5 = '9th grade'  
      6 = '10th grade'  
      7 = '11th grade'  
      8 = '12th grade NO DIPLOMA'  
      9 = 'HIGH SCHOOL GRADUATE - high school DIPLOMA or the equivalent (GED)'  
      10 = 'Some college, no degree'  
      11 = 'Associate degree'  
      12 = 'Bachelors degree'  
      13 = 'Masters degree'  
      14 = 'Professional or Doctorate degree' ;
   value P4_PPEDUCAT
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Less than high school'  
      2 = 'High school'  
      3 = 'Some college'  
      4 = 'Bachelor''s degree or higher' ;
   value P4_PPETHM
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'White, Non-Hispanic'  
      2 = 'Black, Non-Hispanic'  
      3 = 'Other, Non-Hispanic'  
      4 = 'Hispanic'  
      5 = '2+ Races, Non-Hispanic' ;
   value P4_PPHHHEAD
      -2 = 'Not asked'  
      -1 = 'refused'  
      0 = 'No'  
      1 = 'Yes' ;
   value P4_PPHHSIZE
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value P4_PPHOUSE
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'A one-family house detached from any other house'  
      2 = 'A one-family house attached to one or more houses'  
      3 = 'A building with 2 or more apartments'  
      4 = 'A mobile home'  
      5 = 'Boat, RV, van, etc.' ;
   value P4_PPINCIMP
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Less than $5,000'  
      2 = '$5,000 to $7,499'  
      3 = '$7,500 to $9,999'  
      4 = '$10,000 to $12,499'  
      5 = '$12,500 to $14,999'  
      6 = '$15,000 to $19,999'  
      7 = '$20,000 to $24,999'  
      8 = '$25,000 to $29,999'  
      9 = '$30,000 to $34,999'  
      10 = '$35,000 to $39,999'  
      11 = '$40,000 to $49,999'  
      12 = '$50,000 to $59,999'  
      13 = '$60,000 to $74,999'  
      14 = '$75,000 to $84,999'  
      15 = '$85,000 to $99,999'  
      16 = '$100,000 to $124,999'  
      17 = '$125,000 to $149,999'  
      18 = '$150,000 to $174,999'  
      19 = '$175,000 or more' ;
   value P4_PPMARIT
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Married'  
      2 = 'Widowed'  
      3 = 'Divorced'  
      4 = 'Separated'  
      5 = 'Never married'  
      6 = 'Living with partner' ;
   value P4_PPMSACAT
      -2 = 'Not asked'  
      -1 = 'refused'  
      0 = 'Non-Metro'  
      1 = 'Metro' ;
   value P4_PPREG4F
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Northeast'  
      2 = 'Midwest'  
      3 = 'South'  
      4 = 'West' ;
   value P4_PPREG9F
      1 = 'New England'  
      2 = 'Mid-Atlantic'  
      3 = 'East-North Central'  
      4 = 'West-North Central'  
      5 = 'South Atlantic'  
      6 = 'East-South Central'  
      7 = 'West-South Central'  
      8 = 'Mountain'  
      9 = 'Pacific' ;
   value P4_PPRENT
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Owned or being bought by you or someone in your household'  
      2 = 'Rented for cash'  
      3 = 'Occupied without payment of cash rent' ;
   value PPT01F
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value PPT25F
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value PPT612F
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value PPT1317F
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value PPT18OV
      -2 = 'Not asked'  
      -1 = 'refused' ;
   value P4_PPWORK
      -2 = 'Not asked'  
      -1 = 'refused'  
      1 = 'Working - as a paid employee'  
      2 = 'Working - self-employed'  
      3 = 'Not working - on temporary layoff from a job'  
      4 = 'Not working - looking for work'  
      5 = 'Not working - retired'  
      6 = 'Not working - disabled'  
      7 = 'Not working - other' ;
   value P4_PPNET
      0 = 'No'  
      1 = 'Yes' ;
   value PPPA0072F
      -2 = 'Not asked'  
      -1 = 'Refused'  
      1 = 'More than once a week'  
      2 = 'Once a week'  
      3 = 'Once or twice a month'  
      4 = 'A few times a year'  
      5 = 'Once a year or less'  
      6 = 'Never' ;

proc datasets library = library ;
modify wave_4_supplement_v1_2_SAS;
   format w4_xqualified W4_XQUAL.;
   format w4_status W4_STATUS.;
   format w4_complete YES_NO.;
   format w4_source W4_SOURCE.;
   format  w4_xtype W4_XTYPE.;
   format w4_xmonth W4_XMONT.;
   format w4_xmarry W4_XMARR.;
   format w4_xcivil W4_XCIVI.;
   format    w4_xss XSS.;
   format     w4_q1 W4_Q1F.;
   format     w4_q2 W4_Q2F.;
   format w4_quality W4_QUALI.;
   format w4_attractive W4_ATTRA.;
   format w4_attractive_partner W4_ATTRACTIVE_PARTNER.;
   format     w4_q3 W4_Q3F.;
   format     w4_q4 W4_Q4F.;
   format w4_mbtiming_year W4_MBTIM.;
   format w4_mbtiming_month W4_MBTIMING_MONTH.;
   format     w4_q5 YES_NO.;
   format     w4_q6 YES_NO.;
   format     w4_q7 W4_Q7F.;
   format w4_mar_month W4_MAR_M.;
   format   w4_q8_a W4_Q8_A.;
   format   w4_q8_b W4_Q8_B.;
   format     w4_q9 W4_Q9F.;
   format    w4_q10 W4_Q10F.;
   format w4_nonmbtiming_month W4_NMBTIME_MONTH.;
   format w4_broke_up BROKE_UP.;
   format w234_combo_breakup W234_COMBO_BREAKUP.;
   format pp4_ppeduc P4_PPEDUC.;
   format pp4_ppeducat P4_PPEDUCAT.;
   format pp4_ppethm P4_PPETHM.;
   format pp4_pphhhead P4_PPHHHEAD.;
   format pp4_pphhsize P4_PPHHSIZE.;
   format pp4_pphouse P4_PPHOUSE.;
   format pp4_ppincimp P4_PPINCIMP.;
   format pp4_ppmarit P4_PPMARIT.;
   format pp4_ppmsacat P4_PPMSACAT.;
   format pp4_ppreg4 P4_PPREG4F.;
   format pp4_ppreg9 P4_PPREG9F.;
   format pp4_pprent P4_PPRENT.;
   format pp4_ppt01 PPT01F.;
   format pp4_ppt25 PPT25F.;
   format pp4_ppt612 PPT612F.;
   format pp4_ppt1317 PPT1317F.;
   format pp4_ppt18ov PPT18OV.;
   format pp4_ppwork P4_PPWORK.;
   format pp4_ppnet P4_PPNET.;
   format pp4_newer YES_NO.;
   format ppa2009_how_often_services PPPA0072F.;
quit;
